/**
 * =============================================================================
 * OPENAI SERVICE
 * =============================================================================
 *
 * Integration with OpenAI for adversarial critique and consensus.
 *
 * Role in AI Council:
 * -------------------
 * - GPT-4o acts as the "Devil's Advocate" - critiquing PRDs from Gemini
 * - Identifies gaps, ambiguities, and potential issues
 * - Provides counter-arguments and alternative interpretations
 * - Part of the multi-model consensus pattern
 *
 * Why GPT-4o for Critique?
 * ------------------------
 * 1. Strong reasoning capabilities for finding logical gaps
 * 2. Different training data = different blind spots (diversity)
 * 3. Excellent at structured critique and analysis
 * 4. Good at playing devil's advocate role
 *
 * @module services/ai/openai
 */

import { createChildLogger } from '../../lib/logger.js';
import { AppError } from '../../lib/error-handler.js';
import { sanitizeForAI, wrapUserContent } from '../../lib/sanitize.js';
import { retryWithBackoff } from '../../lib/retry.js';
import type { GeneratedPRD } from './gemini.service.js';

/**
 * Critique result from GPT analysis.
 */
export interface CritiqueResult {
  /** Overall assessment */
  overallAssessment: 'approve' | 'needs_revision' | 'reject';

  /** Confidence in the critique (0-1) */
  critiqueConfidence: number;

  /** Issues found */
  issues: Array<{
    severity: 'critical' | 'major' | 'minor';
    category: 'ambiguity' | 'missing' | 'contradiction' | 'scope' | 'feasibility';
    description: string;
    affectedSection: string;
    suggestion?: string;
  }>;

  /** Questions that should be asked */
  clarificationQuestions: string[];

  /** Strengths of the PRD */
  strengths: string[];

  /** Risk areas not addressed */
  missingRisks: string[];

  /** Reasoning for the assessment */
  reasoning: string;
}

/**
 * Consensus vote from a model.
 */
export interface ConsensusVote {
  model: string;
  vote: 'approve' | 'revise' | 'reject';
  confidence: number;
  concerns: string[];
  reasoning: string;
}

/**
 * OpenAI Service for adversarial critique.
 *
 * @example
 * ```typescript
 * const openai = new OpenAIService(apiKey);
 *
 * // Get critique of a PRD
 * const critique = await openai.critiquePRD(prd, transcript);
 *
 * // Check if PRD needs revision
 * if (critique.overallAssessment === 'needs_revision') {
 *   // Handle issues
 * }
 * ```
 */
export class OpenAIService {
  private readonly apiKey?: string;
  private readonly enabled: boolean;
  private readonly logger = createChildLogger({ service: 'OpenAIService' });

  /** Model for critique (o1 series for reasoning) */
  private static readonly CRITIQUE_MODEL = 'gpt-4o';  // Use gpt-4o until o1 is available

  /** API base URL */
  private static readonly BASE_URL = 'https://api.openai.com/v1';

  constructor(apiKey?: string) {
    if (!apiKey) {
      this.enabled = false;
      this.logger.warn('OpenAI service disabled - missing API key');
      return;
    }

    this.enabled = true;
    this.apiKey = apiKey;

    this.logger.info('OpenAI service initialized', {
      model: OpenAIService.CRITIQUE_MODEL,
    });
  }

  /** Check if service is enabled */
  isEnabled(): boolean {
    return this.enabled;
  }

  /**
   * Critique a PRD generated by another model.
   *
   * Acts as adversarial reviewer - looks for problems,
   * gaps, and areas that need clarification.
   *
   * @param prd - The PRD to critique
   * @param originalTranscript - Original meeting transcript for context
   * @returns Critique result with issues and recommendations
   */
  async critiquePRD(
    prd: GeneratedPRD,
    originalTranscript: string
  ): Promise<CritiqueResult> {
    if (!this.enabled) {
      this.logger.warn('OpenAI disabled - returning mock critique');
      return this.getMockCritique();
    }

    const startTime = Date.now();
    this.logger.info('Starting PRD critique', {
      prdTitle: prd.title,
      userStoriesCount: prd.userStories?.length || 0,
      functionalReqsCount: prd.functionalRequirements?.length || 0,
    });

    try {
      const prompt = this.buildCritiquePrompt(prd, originalTranscript);

      const response = await this.callAPI(prompt, {
        temperature: 0.3, // Lower for more consistent critique
        maxTokens: 4096,
      });

      const critique = this.parseCritiqueResponse(response);

      const duration = Date.now() - startTime;
      this.logger.info('PRD critique completed', {
        duration,
        assessment: critique.overallAssessment,
        issueCount: critique.issues.length,
      });

      return critique;

    } catch (error) {
      const duration = Date.now() - startTime;
      this.logger.error('PRD critique failed', {
        duration,
        error: (error as Error).message,
      });

      // Return a cautious critique on failure
      return {
        overallAssessment: 'needs_revision',
        critiqueConfidence: 0.3,
        issues: [{
          severity: 'major',
          category: 'ambiguity',
          description: 'Unable to complete AI critique - manual review required',
          affectedSection: 'all',
        }],
        clarificationQuestions: [],
        strengths: [],
        missingRisks: [],
        reasoning: 'Critique model unavailable - defaulting to manual review',
      };
    }
  }

  /**
   * Vote on whether a PRD should be approved.
   *
   * Used in consensus mechanism where multiple models vote.
   *
   * @param prd - The PRD to vote on
   * @param existingVotes - Votes from other models (for context)
   * @returns This model's vote
   */
  async voteOnPRD(
    prd: GeneratedPRD,
    existingVotes: ConsensusVote[] = []
  ): Promise<ConsensusVote> {
    if (!this.enabled) {
      return {
        model: 'openai-disabled',
        vote: 'approve',
        confidence: 0.5,
        concerns: ['OpenAI not configured - auto-approving'],
        reasoning: 'Service disabled',
      };
    }

    const prompt = this.buildVotePrompt(prd, existingVotes);

    try {
      const response = await this.callAPI(prompt, {
        temperature: 0.2,
        maxTokens: 2048,
      });

      return this.parseVoteResponse(response);
    } catch (error) {
      this.logger.error('Vote failed', { error: (error as Error).message });

      return {
        model: OpenAIService.CRITIQUE_MODEL,
        vote: 'revise',
        confidence: 0.3,
        concerns: ['Unable to complete vote - manual review recommended'],
        reasoning: 'API call failed',
      };
    }
  }

  /**
   * Test connection to OpenAI API.
   */
  async testConnection(): Promise<boolean> {
    if (!this.enabled) return false;

    try {
      await this.callAPI('Say "OK" if you can hear me.', {
        maxTokens: 10,
        temperature: 0,
      });
      return true;
    } catch {
      return false;
    }
  }

  /**
   * Build the adversarial critique prompt.
   */
  private buildCritiquePrompt(prd: GeneratedPRD, transcript: string): string {
    return `# Role: Adversarial PRD Reviewer

You are a senior product manager tasked with CRITICALLY reviewing a PRD.
Your job is to find problems, not to praise. Be thorough and skeptical.

## Your Mission
1. Find gaps, ambiguities, and contradictions
2. Identify missing requirements from the transcript
3. Challenge assumptions and feasibility
4. Point out scope issues (too broad or missing key items)
5. Suggest clarifying questions that should be asked

## PRD to Review
\`\`\`json
${JSON.stringify(prd, null, 2)}
\`\`\`

## Original Meeting Transcript (for comparison)
${wrapUserContent('TRANSCRIPT', sanitizeForAI(transcript, 8000))}

## Output Format (JSON)
\`\`\`json
{
  "overallAssessment": "approve | needs_revision | reject",
  "critiqueConfidence": 0.0-1.0,
  "issues": [
    {
      "severity": "critical | major | minor",
      "category": "ambiguity | missing | contradiction | scope | feasibility",
      "description": "What's wrong",
      "affectedSection": "Which part of PRD",
      "suggestion": "How to fix (optional)"
    }
  ],
  "clarificationQuestions": ["Questions that should be asked"],
  "strengths": ["What's good about the PRD"],
  "missingRisks": ["Risks not mentioned in the PRD"],
  "reasoning": "Your overall analysis"
}
\`\`\`

Be harsh but fair. If the PRD is genuinely good, say so. But find at least 3 areas for improvement.`;
  }

  /**
   * Build the consensus vote prompt.
   */
  private buildVotePrompt(prd: GeneratedPRD, existingVotes: ConsensusVote[]): string {
    let prompt = `# Role: PRD Approval Voter

You are voting on whether this PRD should be approved for development.

## PRD
\`\`\`json
${JSON.stringify(prd, null, 2)}
\`\`\`

`;

    if (existingVotes.length > 0) {
      prompt += `## Other Model Votes
${existingVotes.map(v => `- ${v.model}: ${v.vote} (confidence: ${v.confidence})`).join('\n')}

Consider their concerns but form your own opinion.

`;
    }

    prompt += `## Your Vote (JSON)
\`\`\`json
{
  "vote": "approve | revise | reject",
  "confidence": 0.0-1.0,
  "concerns": ["List of concerns"],
  "reasoning": "Why you voted this way"
}
\`\`\``;

    return prompt;
  }

  /**
   * Call OpenAI API.
   */
  private async callAPI(
    prompt: string,
    options: { temperature?: number; maxTokens?: number } = {}
  ): Promise<string> {
    return retryWithBackoff(
      async () => {
        const response = await fetch(`${OpenAIService.BASE_URL}/chat/completions`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${this.apiKey}`,
          },
          body: JSON.stringify({
            model: OpenAIService.CRITIQUE_MODEL,
            messages: [
              { role: 'user', content: prompt }
            ],
            temperature: options.temperature ?? 0.4,
            max_tokens: options.maxTokens ?? 4096,
          }),
        });

        if (!response.ok) {
          const errorText = await response.text();
          const err = new AppError(
            `OpenAI API error: ${response.status}`,
            502,
            'OPENAI_API_ERROR'
          );
          (err as any).status = response.status;
          throw err;
        }

        const data = await response.json() as {
          choices: Array<{ message: { content: string } }>;
        };

        return data.choices[0]?.message?.content || '';
      },
      { maxRetries: 3, initialDelayMs: 1000, label: 'OpenAI API' },
    );
  }

  /**
   * Parse critique response from JSON.
   */
  private parseCritiqueResponse(text: string): CritiqueResult {
    const jsonMatch = text.match(/```(?:json)?\s*([\s\S]*?)```/);
    const jsonText = jsonMatch ? jsonMatch[1].trim() : text.trim();

    try {
      const parsed = JSON.parse(jsonText);

      return {
        overallAssessment: parsed.overallAssessment || 'needs_revision',
        critiqueConfidence: parsed.critiqueConfidence || 0.5,
        issues: parsed.issues || [],
        clarificationQuestions: parsed.clarificationQuestions || [],
        strengths: parsed.strengths || [],
        missingRisks: parsed.missingRisks || [],
        reasoning: parsed.reasoning || '',
      };
    } catch {
      this.logger.error('Failed to parse critique response');
      throw new AppError('Failed to parse critique', 502, 'PARSE_ERROR');
    }
  }

  /**
   * Parse vote response from JSON.
   */
  private parseVoteResponse(text: string): ConsensusVote {
    const jsonMatch = text.match(/```(?:json)?\s*([\s\S]*?)```/);
    const jsonText = jsonMatch ? jsonMatch[1].trim() : text.trim();

    try {
      const parsed = JSON.parse(jsonText);

      return {
        model: OpenAIService.CRITIQUE_MODEL,
        vote: parsed.vote || 'revise',
        confidence: parsed.confidence || 0.5,
        concerns: parsed.concerns || [],
        reasoning: parsed.reasoning || '',
      };
    } catch {
      throw new AppError('Failed to parse vote', 502, 'PARSE_ERROR');
    }
  }

  /**
   * Return mock critique when disabled.
   */
  private getMockCritique(): CritiqueResult {
    return {
      overallAssessment: 'approve',
      critiqueConfidence: 0.5,
      issues: [{
        severity: 'minor',
        category: 'ambiguity',
        description: 'OpenAI critique disabled - consider enabling for better validation',
        affectedSection: 'configuration',
      }],
      clarificationQuestions: [],
      strengths: ['PRD structure looks complete'],
      missingRisks: [],
      reasoning: 'Mock critique - OpenAI service not configured',
    };
  }
}
